//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db
    {
        public int id { get; set; }
        public string name { get; set; }
        public string doc_type { get; set; }
        public int doc_num { get; set; }
        public string address { get; set; }
        public int phone { get; set; }
        public string email { get; set; }
        public string date { get; set; }
    }
}
